on:
  pull_request:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: tanukiops/dest-repo2/.github/actions/commit-lint@test
        with:
          title: "{{ github.event.pull_request.title }}"
