on:
  pull_request: {}
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache-dependency-path: ".github/workflows/all-pull-requests.yaml"
      - name: Install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest
      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: check PR title
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli \
          && (echo "${TITLE@Q}" | xargs echo | npx commitlint)
