name: Check if pull-request title adheres to conventional commits.
on:
  pull_request:
    types:
      - edited
      - opened
jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: tanukiops/dest-repo2/.github/actions/commit-lint@main
        with:
          title: "${{ github.event.pull_request.title }}"
